# Generated by Django 4.2.3 on 2023-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='default_author.webp', upload_to='author_avatars'),
        ),
    ]
