# Generated by Django 4.2.3 on 2023-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.TextField(default='Book'),
        ),
    ]
