# Generated by Django 4.2.3 on 2023-07-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', 'Started'), ('NP', 'Not paid'), ('C', 'Construct'), ('ID', 'In Delivery'), ('D', 'Delivered'), ('ND', 'Not Delivered')], default='S', max_length=2)),
                ('books', models.ManyToManyField(to='market.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
