# Generated by Django 4.2.3 on 2023-07-26 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_rename_user_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 19, 5, 35, 367234)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('NP', 'Not paid'), ('C', 'Construct'), ('ID', 'In Delivery'), ('D', 'Delivered'), ('ND', 'Not Delivered')], default='Started', max_length=100),
        ),
    ]
