# Generated by Django 4.2.3 on 2023-07-30 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_created_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 18, 51, 28, 523452)),
        ),
    ]
